pipeline {
    agent any
    environment {
        PROJECT_ID = 'vmall-297009'
        CLUSTER_NAME = 'vmall-order-system'
        LOCATION = 'us-central1-c'
        CREDENTIALS_ID = 'gke'
    }
    stages {
        stage("Checkout code") {
            steps {
                checkout scm
            }
        }
        stage("Build image") {
            steps {
                script {
                    sh 'mvn clean'
                    sh 'mvn package'
                    vmall-backend-order = docker.build("fdsxaar/vmall-order-jenkins:${env.BUILD_ID}")
                }
            }
        }
        stage("Push image") {
            steps {
                script {
                    //TODO:check whether image exists in dockerhub
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                            vmall-backend-order.push("${env.BUILD_ID}")
                    }
                }
            }
        }        
        stage('Deploy to GKE') {
            steps{
                sh "sed -i 's/vmall-order-jenkins:latest/vmall-order-jenkins:${env.BUILD_ID}/g' deployment.yaml"
                step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'deployment.yaml', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
            }
        }
    }    
}